package cn.luz.furtalcraft;


import cn.luz.furtalcraft.block.genedreg.AutoGeneratedBlockRegistries;
import cn.luz.mml.neoforge.reg.EnableNeoForgeGeneratedReg;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

@Mod(Constants.MOD_ID)
@EnableNeoForgeGeneratedReg(
        deferredBlock = DeferredBlock.class,
        minecraftBlock = Block.class,
        deferredRegister = DeferredRegister.class,
        deferredRegisterBlock = DeferredRegister.Blocks.class,
        properties = BlockBehaviour.Properties.class,
        resourceKey = ResourceKey.class,
        registries = Registries.class
)
public class FurtalCraft {

    public FurtalCraft(IEventBus eventBus) {
        // This method is invoked by the NeoForge mod loader when it is ready
        // to load your mod. You can access NeoForge and Common code in this
        // project.

        // Use NeoForge to bootstrap the Common mod.
        Constants.LOG.info("Hello NeoForge world!");
        CommonClass.init();
        AutoGeneratedBlockRegistries.BLOCKS.register(eventBus);
    }
}
